name: Build and Push Docker Image

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: pradip100 
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t pradip100/Assignment .
          docker push pradip100/Assignment:latest
